//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class earnings
    {
        public int earningID { get; set; }
        public decimal earnings_total_mes { get; set; }
        public int conteo_facturas { get; set; }
        public Nullable<decimal> utils_total_mes { get; set; }
        public string mes { get; set; }
        public string ano { get; set; }
    }
}
