//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDContext : DbContext
    {
        public BDContext()
            : base("name=BDContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacora> bitacoras { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<direction> directions { get; set; }
        public virtual DbSet<phone> phones { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<sales_x_products> sales_x_products { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<warranty> warranties { get; set; }
        public virtual DbSet<earnings> earnings { get; set; }
    
        public virtual ObjectResult<sp_directions_clients_Result> sp_directions_clients(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("clientID", clientID) :
                new ObjectParameter("clientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_directions_clients_Result>("sp_directions_clients", clientIDParameter);
        }
    
        public virtual ObjectResult<sp_directions_users_Result> sp_directions_users(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_directions_users_Result>("sp_directions_users", userIDParameter);
        }
    
        public virtual ObjectResult<sp_phones_clients_Result> sp_phones_clients(Nullable<int> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("clientID", clientID) :
                new ObjectParameter("clientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_phones_clients_Result>("sp_phones_clients", clientIDParameter);
        }
    
        public virtual ObjectResult<sp_phones_users_Result> sp_phones_users(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_phones_users_Result>("sp_phones_users", userIDParameter);
        }
    
        public virtual ObjectResult<sp_Get_Client_X_Cedula_Result> sp_Get_Client_X_Cedula(string cedulaClient)
        {
            var cedulaClientParameter = cedulaClient != null ?
                new ObjectParameter("cedulaClient", cedulaClient) :
                new ObjectParameter("cedulaClient", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_Client_X_Cedula_Result>("sp_Get_Client_X_Cedula", cedulaClientParameter);
        }
    
        public virtual ObjectResult<sp_Get_User_X_Cedula_Result> sp_Get_User_X_Cedula(string cedulaUser)
        {
            var cedulaUserParameter = cedulaUser != null ?
                new ObjectParameter("cedulaUser", cedulaUser) :
                new ObjectParameter("cedulaUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_User_X_Cedula_Result>("sp_Get_User_X_Cedula", cedulaUserParameter);
        }
    
        public virtual ObjectResult<sp_Get_producto_x_nombre_Result> sp_Get_producto_x_nombre(string nombre_producto)
        {
            var nombre_productoParameter = nombre_producto != null ?
                new ObjectParameter("nombre_producto", nombre_producto) :
                new ObjectParameter("nombre_producto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_producto_x_nombre_Result>("sp_Get_producto_x_nombre", nombre_productoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ultimoID_sales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ultimoID_sales");
        }
    
        public virtual ObjectResult<string> sp_getRolesForUser(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_getRolesForUser", userNameParameter);
        }
    
        public virtual ObjectResult<string> sp_getUsuariosRole(string roleName)
        {
            var roleNameParameter = roleName != null ?
                new ObjectParameter("roleName", roleName) :
                new ObjectParameter("roleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_getUsuariosRole", roleNameParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> sp_isUserInRole(string userName, string roleName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("roleName", roleName) :
                new ObjectParameter("roleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("sp_isUserInRole", userNameParameter, roleNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Get_Last_SaleID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Get_Last_SaleID");
        }
    
        public virtual int sp_Analytics_Earnings(string ano_Mes, Nullable<bool> rep_mes)
        {
            var ano_MesParameter = ano_Mes != null ?
                new ObjectParameter("Ano_Mes", ano_Mes) :
                new ObjectParameter("Ano_Mes", typeof(string));
    
            var rep_mesParameter = rep_mes.HasValue ?
                new ObjectParameter("rep_mes", rep_mes) :
                new ObjectParameter("rep_mes", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Analytics_Earnings", ano_MesParameter, rep_mesParameter);
        }
    
        public virtual int sp_Analytics_Show(Nullable<int> compraID, ObjectParameter z_Vent_Tot, ObjectParameter z_Util_Tot)
        {
            var compraIDParameter = compraID.HasValue ?
                new ObjectParameter("compraID", compraID) :
                new ObjectParameter("compraID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Analytics_Show", compraIDParameter, z_Vent_Tot, z_Util_Tot);
        }
    
        public virtual ObjectResult<sp_Get_factura_detalle_Result> sp_Get_factura_detalle(Nullable<int> maestroID)
        {
            var maestroIDParameter = maestroID.HasValue ?
                new ObjectParameter("maestroID", maestroID) :
                new ObjectParameter("maestroID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_factura_detalle_Result>("sp_Get_factura_detalle", maestroIDParameter);
        }
    }
}
