//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone
    {
        public int telefonoID { get; set; }
        public int relacionID { get; set; }
        public string tabla_relacion { get; set; }
        public string telefono { get; set; }
    }
}
