//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.sales_x_products = new HashSet<sales_x_products>();
        }
    
        public int productID { get; set; }
        public string codigo_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public int cantidad { get; set; }
        public Nullable<decimal> precio_manufactura { get; set; }
        public decimal precio_venta { get; set; }
        public string estado_producto { get; set; }
        public decimal porcentaje_ganancia { get; set; }
        public Nullable<decimal> porcentaje_descuento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sales_x_products> sales_x_products { get; set; }
    }
}
