//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_x_products
    {
        public int compraID_detalle { get; set; }
        public int compraID { get; set; }
        public int productID { get; set; }
        public decimal precio_factura_d { get; set; }
        public int cantidad { get; set; }
    
        public virtual product product { get; set; }
        public virtual sale sale { get; set; }
    }
}
