//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.sales = new HashSet<sale>();
            this.Roles = new HashSet<Role>();
        }
    
        public int userID { get; set; }
        public string cedula_user { get; set; }
        public string primer_nombre_user { get; set; }
        public string segundo_nombre_user { get; set; }
        public string primer_apellido_user { get; set; }
        public string segundo_apellido_user { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public string tipo_user { get; set; }
        public string estado_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale> sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
