//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class warranty
    {
        public int warrantyID { get; set; }
        public int compraID { get; set; }
        public string estado_warranty { get; set; }
    
        public virtual sale sale { get; set; }
    }
}
