//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_x_products
    {
        public int compraID_detalle { get; set; }
        public int compraID { get; set; }
        public int productID { get; set; }
        public decimal precio_factura_d { get; set; }
    
        public virtual product product { get; set; }
        public virtual sale sale { get; set; }
    }
}
